#!/usr/bin/env python3
"""
build_gdal_commands.py v3.0 — Ciuccio Upgrade
Forlì Digital Twin — Master v3.3

Genera lo script shell con i comandi gdal_translate + gdalwarp
per produrre i GeoTIFF finali in EPSG:25832.
"""

from pathlib import Path
import csv
from collections import defaultdict
from datetime import datetime

ROOT = Path(__file__).resolve().parents[2]
GCP_CSV = ROOT / "04_GCP_GEOREF" / "GCP_FINAL_VERIFIED.csv"
OUT_SCRIPT = ROOT / "13_PIPELINE" / "scripts" / "gdal_georef_final_commands.sh"
OUT_DIR = ROOT / "11_FINAL_OUTPUT" / "geotiff_final"

SHEET_TO_FILE = {
    "FO004_042": "02_RASTER_STORICI/CT_FO004_042.jpg",
    "FO004_043": "02_RASTER_STORICI/01CT_FO004_043.jpg",
    "FO004_044": "02_RASTER_STORICI/CT_FO004_044.jpg",
    "FO004_045": "02_RASTER_STORICI/CT_FO004_045.jpg",
}

MIN_GCP = 8


def main():
    if not GCP_CSV.exists():
        print(f"[ERRORE] Manca {GCP_CSV}")
        print("         Esegui prima export_gcp_verified.py o promote_verified_gcps.py")
        raise SystemExit(1)

    rows_by_sheet = defaultdict(list)
    with GCP_CSV.open(encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            if r.get("decision") != "KEEP":
                continue
            if not r.get("target_easting_epsg25832") or not r.get("target_northing_epsg25832"):
                continue
            rows_by_sheet[r["sheet_id"]].append(r)

    cmds = [
        "#!/bin/bash",
        "# Auto-generated by build_gdal_commands.py v3.0 (Ciuccio)",
        f"# Generated: {datetime.now().isoformat(timespec='seconds')}",
        "set -euo pipefail",
        "",
        f"mkdir -p \"{OUT_DIR}\"",
        "echo \"[INFO] Output directory: " + str(OUT_DIR) + "\"",
        ""
    ]

    ready_sheets = 0
    for sheet, rows in sorted(rows_by_sheet.items()):
        if len(rows) < MIN_GCP:
            print(f"[WARN] {sheet}: solo {len(rows)} GCP validi (minimo {MIN_GCP}). Saltato.")
            cmds.append(f"# SKIP {sheet}: solo {len(rows)} GCP")
            continue

        src = SHEET_TO_FILE.get(sheet)
        if not src:
            print(f"[WARN] Nessun file raster mappato per {sheet}")
            continue

        tmp = OUT_DIR / f"{sheet}_with_gcps.tif"
        out = OUT_DIR / f"{sheet}_FINAL_EPSG25832.tif"

        gcps = []
        for r in rows:
            gcps.append(
                f'-gcp {r["source_x"]} {r["source_y"]} '
                f'{r["target_easting_epsg25832"]} {r["target_northing_epsg25832"]}'
            )

        cmds.append(f"echo \"[STEP] Georeferenziazione {sheet} ({len(rows)} GCP)...\"")
        cmds.append(
            f'gdal_translate -of GTiff -a_srs EPSG:25832 \\\n'
            f'  {" ".join(gcps)} \\\n'
            f'  "{src}" "{tmp}"'
        )
        cmds.append(
            f'gdalwarp -r cubic -tps -t_srs EPSG:25832 \\\n'
            f'  -co COMPRESS=DEFLATE -co PREDICTOR=2 -co TILED=YES -co BIGTIFF=IF_SAFER \\\n'
            f'  "{tmp}" "{out}"'
        )
        cmds.append(f'gdaladdo -r average "{out}" 2 4 8 16')
        cmds.append(f'rm -f "{tmp}"')
        cmds.append(f'echo "[OK] Creato: {out}"')
        cmds.append("")
        ready_sheets += 1

    cmds.append("echo \"==============================================\"")
    cmds.append(f"echo \"GeoTIFF generati: {ready_sheets} fogli\"")
    cmds.append("echo \"Directory: " + str(OUT_DIR) + "\"")
    cmds.append("echo \"==============================================\"")

    OUT_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    OUT_SCRIPT.write_text("\n".join(cmds) + "\n", encoding="utf-8")
    OUT_SCRIPT.chmod(0o755)

    print(f"[OK] Creato: {OUT_SCRIPT}")
    print(f"     Fogli pronti: {ready_sheets}")
    if ready_sheets == 0:
        print("[ATTENZIONE] Nessun foglio ha abbastanza GCP KEEP. Completa il matching.")
        raise SystemExit(2)


if __name__ == "__main__":
    main()
